# Generated by Django 4.1 on 2022-08-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default='Entry title', max_length=500),
            preserve_default=False,
        ),
    ]
